//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FareRules
    {
        public string fare_id { get; set; }
        public string route_id { get; set; }
        public string origin_id { get; set; }
        public string destination_id { get; set; }
        public string contains_id { get; set; }
    
        internal virtual FareAttributes fare_attributes { get; set; }
        internal virtual Route route { get; set; }
    }
}
