//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelling.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GtfsEntities : DbContext
    {
        public GtfsEntities()
            : base("name=GtfsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Agency> agencies { get; set; }
        public DbSet<Calendar> calendar { get; set; }
        public DbSet<Frequency> frequencies { get; set; }
        public DbSet<Route> routes { get; set; }
        public DbSet<Shape> shapes { get; set; }
        public DbSet<StopTime> stop_times { get; set; }
        public DbSet<Stop> Stops { get; set; }
        public DbSet<Transfer> transfers { get; set; }
        public DbSet<Trip> trips { get; set; }
    }
}
