//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public Stop()
        {
            this.stop_times = new HashSet<StopTime>();
            this.transfer = new HashSet<Transfer>();
            this.transfer1 = new HashSet<Transfer>();
        }
    
        public string stop_id { get; set; }
        public string stop_name { get; set; }
        public string stop_desc { get; set; }
        public double stop_lat { get; set; }
        public double stop_lon { get; set; }
        public string location_type { get; set; }
        public string parent_station { get; set; }
        public string zone_id { get; set; }
        public string stop_url { get; set; }
    
        internal virtual ICollection<StopTime> stop_times { get; set; }
        internal virtual ICollection<Transfer> transfer { get; set; }
        internal virtual ICollection<Transfer> transfer1 { get; set; }
    }
}
