//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stop
    {
        public Stop()
        {
            this.stop_times = new HashSet<StopTime>();
            this.transfers_from = new HashSet<Transfer>();
            this.transfers_to = new HashSet<Transfer>();
        }
    
        public string stop_id { get; set; }
        public string stop_code { get; set; }
        public string stop_name { get; set; }
        public string stop_desc { get; set; }
        public Nullable<decimal> stop_lat { get; set; }
        public Nullable<decimal> stop_lon { get; set; }
        public string zone_id { get; set; }
        public string stop_url { get; set; }
        public string location_type { get; set; }
        public string parent_station { get; set; }
        public string stop_timezone { get; set; }
        public string wheelchair_boarding { get; set; }
        public string wheelchair_accessible { get; set; }
    
        internal virtual ICollection<StopTime> stop_times { get; set; }
        internal virtual ICollection<Transfer> transfers_from { get; set; }
        internal virtual ICollection<Transfer> transfers_to { get; set; }
    }
}
