//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainModelling.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trip
    {
        public trip()
        {
            this.frequencies = new HashSet<frequency>();
            this.stop_times = new HashSet<stop_times>();
        }
    
        public string trip_id { get; set; }
        public string service_id { get; set; }
        public string route_id { get; set; }
        public string trip_headsign { get; set; }
        public Nullable<int> direction_id { get; set; }
        public string block_id { get; set; }
        public string shape_id { get; set; }
    
        public virtual ICollection<frequency> frequencies { get; set; }
        public virtual route route { get; set; }
        public virtual ICollection<stop_times> stop_times { get; set; }
    }
}
